services:
  notebooks:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/kubyterlab-llm:25.02
    ports:
      - "127.0.0.1:8888:8888"
    container_name: kubyterlab
    networks:
      - eberron-llm
    environment:
      - JUPYTERLAB_SETTINGS_DIR=/jupyterlab/config
      - HF_HOME=/jupyterlab/hf
      - MISTRAL_MODEL=/jupyterlab/mistral_models
      - TESSDATA_PREFIX=/usr/local/share/tessdata/
      - ARTEFACT_ROOT_FOLDER=/jupyterlab/notebooks/
    volumes:
      - './jupyterlab/notebooks:/jupyterlab/notebooks'
      - 'D:/Home/Personal/RP/Resources/DND 3e/Eberron:/eberron/3e'
      - 'D:/Home/Personal/RP/Resources/DND 5e/CampaignSettings/Eberron:/eberron/5e'
      - 'D:/Home/Personal/RP/Resources/DND 5e/CoreRulebooks:/core/5e'
      - 'D:/Home/Personal/RP/Resources/DND 5e/Homebrew:/homebrew/5e'
      - './jupyterlab/config:/jupyterlab/config'
      - 'F:/HuggingFaceCache:/jupyterlab/hf'
      - 'F:/MistralModels:/jupyterlab/mistral_models'
      - 'D:/AppData/EberronCorpus:/corpus'
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - eberron-llm
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
  embed:
    image: ollama/ollama:latest
    container_name: embed
    ports:
      - "11435:11434"
    volumes:
      - ./embed/ollama:/root/.ollama
      - ./embed/entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - eberron-llm
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    networks:
      - eberron-llm
networks:
  eberron-llm:
    driver: bridge