services:
  notebooks:
    image: kubyterlab
    build:
      context: ./
      dockerfile: jupyterlab/Dockerfile
    ports:
      - "127.0.0.1:8888:8888"
    container_name: kubyterlab
    networks:
      - eberron-llm
    environment:
      - JUPYTERLAB_SETTINGS_DIR=/jupyterlab/config
      - HF_HOME=/jupyterlab/hf
      - MISTRAL_MODEL=/jupyterlab/mistral_models
      - TESSDATA_PREFIX=/usr/local/share/tessdata/
    volumes:
      - './jupyterlab/notebooks:/jupyterlab/notebooks'
      - 'D:/Home/Personal/RP/Resources/DND 3e/Eberron:/eberron/3e'
      - 'D:/Home/Personal/RP/Resources/DND 5e/CampaignSettings/Eberron:/eberron/5e'
      - './jupyterlab/config:/jupyterlab/config'
      - 'F:/HuggingFaceCache:/jupyterlab/hf'
      - 'F:/MistralModels:/jupyterlab/mistral_models'
      - 'D:/AppData/EberronCorpus:/corpus'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
networks:
  eberron-llm:
    driver: bridge