services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    container_name: eberron_agent_frontend
    ports:
      - "8501:8501"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    privileged: true
    container_name: eberron_agent_frontend_test
    depends_on:
      frontend:
        condition: service_healthy

